import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata = {
  title: "verifake | deepfake image detection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="backdrop-blur">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
